name: Janes Total Wellness workflow

on: 
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      - name: Installing dependencies
        run: npm install
      - name: Checking code format
        run: npm run eslint
      - name: Building for production
        run: npm run build
      - name: Running local unit tests
        run: npm run test
        if: ${{ !contains(join(github.event.commits.*.message, ', '), 'skip_test') }}
        env:
          NODE_ENV: "test"
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}


      - name: Runing Cypress tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test, npm start
          wait-on: "http://localhost:3001"
        if: ${{ !contains(join(github.event.commits.*.message, ', '), 'skip_test') }}
        env:
          NODE_ENV: "test"
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
      - name: Bump version and push tag
        # run: git tag ${{ github.event.inputs.version }}
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "#patch"
      - name: Deployment to Heroku Apps
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jane-wellness-app" # Must be unique in Heroku
          heroku_email: "sirpaquillo1@yahoo.com.mx"
          dontuseforce: false
          procfile: "web: npm run production"
          healthcheck: "https://jane-wellness-app.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
